//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demovar5
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupPoints
    {
        public PickupPoints()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int PickupPointID { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
