//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demovar5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        public Units()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int UnitID { get; set; }
        public string UnitName { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
